spring:
 datasource:
   url: jdbc:h2:mem:test
   username: ruggero
   password: 1234
   driver-class-name: org.h2.Driver

 h2:
   console:
     enabled: true

 jpa:
   show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE