spring:
 datasource:
   url: jdbc:h2:mem:test
   username: ruggero
   password: 1234
   driver-class-name: org.h2.Driver

 h2:
   console:
     enabled: true

 jpa:
   show-sql: true

 thymeleaf:
   check-template-location: false

# jackson:
#   default-property-inclusion: non_null

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE